# Generated by Django 3.0.1 on 2020-03-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFID', models.CharField(max_length=20)),
                ('ProductID', models.CharField(max_length=20, unique=True)),
                ('ProductName', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
                ('Description', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('RFID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('RegDate', models.DateField()),
                ('OwnerName', models.CharField(max_length=20, null=True)),
                ('Company', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
                ('Type', models.CharField(max_length=20, null=True)),
                ('About', models.CharField(max_length=100, null=True)),
                ('Password', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=20)),
                ('FatherName', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('BirthDate', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=12)),
                ('CollegeID', models.CharField(max_length=10)),
                ('CollegeName', models.CharField(max_length=20)),
                ('EnrollNum', models.CharField(max_length=15, unique=True)),
                ('RFID', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
