# Generated by Django 3.0.1 on 2020-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusiInfoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Email',
            field=models.EmailField(default='default@mail.com', max_length=254, unique=True),
        ),
    ]
