# Generated by Django 3.0.1 on 2020-03-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusiInfoApp', '0003_auto_20200311_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Email',
            new_name='Mobile',
        ),
    ]
