# Generated by Django 3.0.1 on 2020-03-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusiInfoApp', '0005_auto_20200311_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
